name: Minify HTML, CSS & JS

on:
  push:
    branches:
      - main  # Change selon ta branche principale

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Minify files
        uses: docker://devatherock/minify-js-css-html

      - name: Commit minified files
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Minified files" || echo "No changes to commit"
          git push
